### ISSUE TITLE
Лишняя магия — приоритеты блоков

### ISSUE THREAD

**Issue by glukki** [pasaran/descript#107]
Зачем сия магия? Это же только вводит людей в недоумение.
```
{
    foo: object({
        bar: 'bar.jsx',
        boo: 'boo.jsx'
    }) +20,

    bar: array([
        'foo.jsx'
    ]) +10,

    baz: 'baz.jsx'
}
```

На мой взгляд, намного понятнее традиционная декларативная запись, хотя бы даже следующего вида:
```
{
    foo: {
        value: {
            bar: 'bar.jsx',
            boo: 'boo.jsx'
        },
        priority: 20
    },

    bar: {
        value: [
            'foo.jsx'
        ],
        priority: 10
    },

    baz: 'baz.jsx'
}
```

Пример взят [отсюда](https://github.com/pasaran/descript/wiki/syntax#%D0%9F%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%D1%8B-%D0%B1%D0%BB%D0%BE%D0%BA%D0%BE%D0%B2)

**Comment by chestozo** [comment]
Ты пока первый, кто жалуется, остальным это показалось "прикольно" )
+ это валидный javascript, магии тут нет.

**Comment by Rebulus** [comment]
Штука валидная, но требует все равно предварительного парсинга от descript, а потом уже исполнения. Соглашусь с Виталием, не читаемо :+1:

**Comment by pasaran** [comment]
Ну так не пользуйтесь этим вариантом. Пользуйтесь скучным и нудным:

```
{
    foo: object({
        bar: 'bar.jsx',
        boo: 'boo.jsx'
    }, { priority: 20 }),

    bar: array([
        'foo.jsx'
    ], { priority: 10 }),

    baz: 'baz.jsx'
}
```

**Comment by chestozo** [comment]
> требует все равно предварительного парсинга от descript

Ну это один раз делается во время инициализации блока.
Кажется, немного накладных расходов.

Эта запись позволяет компактно писать вызовы блоков типа такого:
```js
// компактиш
{
    first: de.call('ya:foo()') +10,
    second: de.call('ya:bar()')
}

// читаемиш
{
    first: de.call('ya:foo()', { priority: 10 }),
    second: de.call('ya:bar()')
}
```
Не знаю, что скажет автор идеи )
