### ISSUE TITLE
Поддержка асинхронного result() у блоков

### ISSUE THREAD

**Issue by glukki** [pasaran/descript#111]
Мне надо конвертнуть xml ответ от ручки в js-объект, но примерно все парсеры xml асинхронны, а result не поддерживает callback.
Что делать?

**Comment by pasaran** [comment]
Ммм. Можно call-блок сделать, наверное.
Это просто js-модуль с определенным интерфейсом, он может вернуть promise. И там внутри что угодно можно сделать.

Ну или попробовать допилить немного result, чтобы он принимал функцию, а если функция вернет promise, то действовать соответствующим образом.

**Comment by pasaran** [comment]
@chestozo, расскажи, как модули делать. Я уже не помню )

**Comment by chestozo** [comment]
Как-то так:
```js
// config.js
{
    "modules": {
        "foo": "./path/to/module.js"
    }
}

// ./path/to/module.js 
module.exports = {
    bar: function(params, context) {
        return no.Promise.resolved(
            new de.Result.Value({ truth: 42 })
        );
    }
};

// handler.jsx
'foo:bar()'
```

**Comment by glukki** [comment]
ой, да, спасибо, я тогда смог сам разобраться :)
