### ISSUE TITLE
Выполнять before до guard

### ISSUE THREAD

**Issue by vitkarpov** [pasaran/descript#116]
Иногда, хочется вычислить что-то в before блока и решить на основе этих данных выполнять блок или нет. Сейчас этого сделать нельзя, потому что [guard выполняется до before](https://github.com/pasaran/descript/blob/master/lib/de.block.js#L226-L233).

**Comment by chestozo** [comment]
Кажется, это ок.
В любом случае нужна чёткая последовательность что за чем.
`before` до `guard` кажется странным вариантом.

**Comment by pasaran** [comment]
Ну, были какие-то причины, почему порядок такой. Но я их не помню )

А что мешает вычислить это самое прямо в гварде? Там же можно использовать обычную функцию вроде бы.
https://github.com/pasaran/descript/blob/master/lib/de.block.js#L55

**Comment by vitkarpov** [comment]
Да, действительно, можно вычислить все в гарде и положить в стейт.

Сперва показалось логичным, чтобы before выполнялся до всего, но потом понял, что если гард вернет false, до before все равно будет выполняться, а это уже как-то не очень (блок не выполнится, а before зачем-то выполнится)

Спасибо.
