### ISSUE TITLE
Не накладывать шаблон, если вернули 404, 500 или 302 статусы

### ISSUE THREAD

**Issue by vitkarpov** [pasaran/descript#119]
Если сделали `setStatus`, нужно ли накладывать шаблон? Кажется, лишняя работа.

**Comment by pasaran** [comment]
Да. По идее не нужно

-- 
Sergei Nikitin

**Comment by alexeyten** [comment]
Вообще зависит от. Мы, например, рисуем собственную 404 в некоторых местах. Видимо нужно как-то уметь этим управлять.

**Comment by vitkarpov** [comment]
Насколько я понимаю, если result будет экземпляром `de.Result.Error`, то шаблон выполняться не будет.
Тогда может как-то так можно контролировать:

```js
{
    result: function(data, context) {
        // например, если есть редирект
        if (context.response.location) {
            return de.error();
        }
        return data;
    }
}
```

?

**Comment by vitkarpov** [comment]
Хотя, выглядит как хак

**Comment by alexeyten** [comment]
Не выйдет
https://github.com/pasaran/descript/blob/master/lib/de.block.js#L345

**Comment by vitkarpov** [comment]
ага, точно

**Comment by pasaran** [comment]
Ладно. Я как раз собираюсь сделать второй подход к снаряду и сделать descript 2.0 )
Видимо, нужно и так, и так уметь.

**Comment by vitkarpov** [comment]
Ок. Закрываем тогда.
