### ISSUE TITLE
PATCH теряет body

### ISSUE THREAD

**Issue by Diokuz** [pasaran/descript#123]
При замене метода POST (или PUT, не суть) на PATCH, на сервер перестаёт улетать body запроса.

Что-то с этим можно сделать с моей стороны, или это баг в либе?

```js
de.http('http://requestb.in/1h0ll921', {
    'method': 'PATCH',
    'headers': {
        'Content-Type': 'application/json'
    },
    'body': 'qwe'
})
```

**Comment by pasaran** [comment]
Ну, баг не баг, но да, вот эта строчка:
https://github.com/pasaran/descript/blob/master/lib/de.http.js#L27

Как по мне, так все, кроме get и post — хипстерское баловство :)
